classDiagram

class Player {
    ...
    +mediaLoadStrategy: firstCanPlay | MediaLoadStrategy
}

class MediaController {
    <<interface>>
    getLoaders() MediaLoader[]
    setCurrentLoader(loader: MediaLoader) void
}

MediaController--> MediaLoader
Player --> MediaController: implements

class MediaLoader {
    <<interface>>
    ID: string
    canPlay(src: Source[]) boolean
    loadMedia(src: Source[]) Promise~void~
}

class MediaLoadStrategy~T extends MediaLoader~ {
    <<interface>>
    register(controller: MediaController) void
    onSrcChange(src: Source[]) Promise~void~
    renderWhileLoading() TemplateResult
}

class FirstCanPlayMediaLoadStrategy

MediaLoadStrategy <-- FirstCanPlayMediaLoadStrategy: implements

Player -- MediaLoadStrategy: use
Player "1" --* "0..*" MediaProvider: composition

MediaProvider --> MediaLoader: implements