/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimePlaybackControlProps {
  
  /** The URL to an SVG element or fragment to load. */
  playIcon?: Components.VimePlaybackControl["playIcon"]
  
  /** The URL to an SVG element or fragment to load. */
  pauseIcon?: Components.VimePlaybackControl["pauseIcon"]
  
  /** The direction in which the tooltip should grow. */
  tooltipDirection?: Components.VimePlaybackControl["tooltipDirection"]
  
  /** Whether the tooltip should not be displayed. */
  hideTooltip?: Components.VimePlaybackControl["hideTooltip"]
  
  /** Scale the size of the control up/down by the amount given. */
  scale?: Components.VimePlaybackControl["scale"]
  
  /** A slash (`/`) separated string of JS keyboard keys (`KeyboardEvent.key`), that when caught in
a `keydown` event, will trigger a `click` event on the control. */
  keys?: Components.VimePlaybackControl["keys"]
  
  /**  */
  paused?: Components.VimePlaybackControl["paused"]
  
  /**  */
  i18n?: Components.VimePlaybackControl["i18n"]
}

interface VimePlaybackControlEvents {
  
}

interface VimePlaybackControlSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_playback_control;
	let current;
	const default_slot_template = /*$$slots*/ ctx[11].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[10], null);

	return {
		c() {
			vime_playback_control = element("vime-playback-control");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_playback_control, "play-icon", /*playIcon*/ ctx[0]);
			set_custom_element_data(vime_playback_control, "pause-icon", /*pauseIcon*/ ctx[1]);
			set_custom_element_data(vime_playback_control, "tooltip-direction", /*tooltipDirection*/ ctx[2]);
			set_custom_element_data(vime_playback_control, "hide-tooltip", /*hideTooltip*/ ctx[3]);
			set_custom_element_data(vime_playback_control, "scale", /*scale*/ ctx[4]);
			set_custom_element_data(vime_playback_control, "keys", /*keys*/ ctx[5]);
			set_custom_element_data(vime_playback_control, "paused", /*paused*/ ctx[6]);
		},
		m(target, anchor) {
			insert(target, vime_playback_control, anchor);

			if (default_slot) {
				default_slot.m(vime_playback_control, null);
			}

			/*vime_playback_control_binding*/ ctx[12](vime_playback_control);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 1024) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[10], dirty, null, null);
				}
			}

			if (!current || dirty & /*playIcon*/ 1) {
				set_custom_element_data(vime_playback_control, "play-icon", /*playIcon*/ ctx[0]);
			}

			if (!current || dirty & /*pauseIcon*/ 2) {
				set_custom_element_data(vime_playback_control, "pause-icon", /*pauseIcon*/ ctx[1]);
			}

			if (!current || dirty & /*tooltipDirection*/ 4) {
				set_custom_element_data(vime_playback_control, "tooltip-direction", /*tooltipDirection*/ ctx[2]);
			}

			if (!current || dirty & /*hideTooltip*/ 8) {
				set_custom_element_data(vime_playback_control, "hide-tooltip", /*hideTooltip*/ ctx[3]);
			}

			if (!current || dirty & /*scale*/ 16) {
				set_custom_element_data(vime_playback_control, "scale", /*scale*/ ctx[4]);
			}

			if (!current || dirty & /*keys*/ 32) {
				set_custom_element_data(vime_playback_control, "keys", /*keys*/ ctx[5]);
			}

			if (!current || dirty & /*paused*/ 64) {
				set_custom_element_data(vime_playback_control, "paused", /*paused*/ ctx[6]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_playback_control);
			if (default_slot) default_slot.d(detaching);
			/*vime_playback_control_binding*/ ctx[12](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { playIcon = undefined } = $$props;
	let { pauseIcon = undefined } = $$props;
	let { tooltipDirection = undefined } = $$props;
	let { hideTooltip = undefined } = $$props;
	let { scale = undefined } = $$props;
	let { keys = undefined } = $$props;
	let { paused = undefined } = $$props;
	let { i18n = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(13, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(7, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_playback_control_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(7, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("playIcon" in $$props) $$invalidate(0, playIcon = $$props.playIcon);
		if ("pauseIcon" in $$props) $$invalidate(1, pauseIcon = $$props.pauseIcon);
		if ("tooltipDirection" in $$props) $$invalidate(2, tooltipDirection = $$props.tooltipDirection);
		if ("hideTooltip" in $$props) $$invalidate(3, hideTooltip = $$props.hideTooltip);
		if ("scale" in $$props) $$invalidate(4, scale = $$props.scale);
		if ("keys" in $$props) $$invalidate(5, keys = $$props.keys);
		if ("paused" in $$props) $$invalidate(6, paused = $$props.paused);
		if ("i18n" in $$props) $$invalidate(8, i18n = $$props.i18n);
		if ("$$scope" in $$props) $$invalidate(10, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, i18n*/ 8448) {
			$: if (__mounted) setProp("i18n", i18n);
		}
	};

	return [
		playIcon,
		pauseIcon,
		tooltipDirection,
		hideTooltip,
		scale,
		keys,
		paused,
		__ref,
		i18n,
		getWebComponent,
		$$scope,
		$$slots,
		vime_playback_control_binding
	];
}

class VimePlaybackControl extends SvelteComponent {
  $$prop_def: VimePlaybackControlProps;
  $$events_def: VimePlaybackControlEvents;
  $$slot_def: VimePlaybackControlSlots;

  $on<K extends keyof VimePlaybackControlEvents>(type: K, callback: (e: VimePlaybackControlEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimePlaybackControlProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			playIcon: 0,
			pauseIcon: 1,
			tooltipDirection: 2,
			hideTooltip: 3,
			scale: 4,
			keys: 5,
			paused: 6,
			i18n: 8,
			getWebComponent: 9
		});
	}

	get getWebComponent(): HTMLVimePlaybackControlElement | undefined {
		return this.$$.ctx[9];
	}
}

export default VimePlaybackControl;