/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeVideoProps {
  
  /**  */
  willAttach?: Components.VimeVideo["willAttach"]
  
  /** Whether to use CORS to fetch the related image. See
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) for more
information. */
  crossOrigin?: Components.VimeVideo["crossOrigin"]
  
  /** Provides a hint to the browser about what the author thinks will lead to the best user
experience with regards to what content is loaded before the video is played. See
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload) for more
information. */
  preload?: Components.VimeVideo["preload"]
  
  /** A URL for an image to be shown while the video is downloading. If this attribute isn't
specified, nothing is displayed until the first frame is available, then the first frame is
shown as the poster frame. */
  poster?: Components.VimeVideo["poster"]
  
  /** Determines what controls to show on the media element whenever the browser shows its own set
of controls (e.g. when the controls attribute is specified). */
  controlsList?: Components.VimeVideo["controlsList"]
  
  /** **EXPERIMENTAL:** Whether the browser should automatically toggle picture-in-picture mode as
the user switches back and forth between this document and another document or application. */
  autoPiP?: Components.VimeVideo["autoPiP"]
  
  /** **EXPERIMENTAL:** Prevents the browser from suggesting a picture-in-picture context menu or to
request picture-in-picture automatically in some cases. */
  disablePiP?: Components.VimeVideo["disablePiP"]
  
  /** **EXPERIMENTAL:** Whether to disable the capability of remote playback in devices that are
attached using wired (HDMI, DVI, etc.) and wireless technologies
(Miracast, Chromecast, DLNA, AirPlay, etc). */
  disableRemotePlayback?: Components.VimeVideo["disableRemotePlayback"]
  
  /** The title of the current media. */
  mediaTitle?: Components.VimeVideo["mediaTitle"]
}

interface VimeVideoEvents {
  
}

interface VimeVideoSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_video;
	let current;
	const default_slot_template = /*$$slots*/ ctx[13].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[12], null);

	return {
		c() {
			vime_video = element("vime-video");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_video, "will-attach", /*willAttach*/ ctx[0]);
			set_custom_element_data(vime_video, "cross-origin", /*crossOrigin*/ ctx[1]);
			set_custom_element_data(vime_video, "preload", /*preload*/ ctx[2]);
			set_custom_element_data(vime_video, "poster", /*poster*/ ctx[3]);
			set_custom_element_data(vime_video, "controls-list", /*controlsList*/ ctx[4]);
			set_custom_element_data(vime_video, "auto-pip", /*autoPiP*/ ctx[5]);
			set_custom_element_data(vime_video, "disable-pip", /*disablePiP*/ ctx[6]);
			set_custom_element_data(vime_video, "disable-remote-playback", /*disableRemotePlayback*/ ctx[7]);
			set_custom_element_data(vime_video, "media-title", /*mediaTitle*/ ctx[8]);
		},
		m(target, anchor) {
			insert(target, vime_video, anchor);

			if (default_slot) {
				default_slot.m(vime_video, null);
			}

			/*vime_video_binding*/ ctx[14](vime_video);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4096) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[12], dirty, null, null);
				}
			}

			if (!current || dirty & /*willAttach*/ 1) {
				set_custom_element_data(vime_video, "will-attach", /*willAttach*/ ctx[0]);
			}

			if (!current || dirty & /*crossOrigin*/ 2) {
				set_custom_element_data(vime_video, "cross-origin", /*crossOrigin*/ ctx[1]);
			}

			if (!current || dirty & /*preload*/ 4) {
				set_custom_element_data(vime_video, "preload", /*preload*/ ctx[2]);
			}

			if (!current || dirty & /*poster*/ 8) {
				set_custom_element_data(vime_video, "poster", /*poster*/ ctx[3]);
			}

			if (!current || dirty & /*controlsList*/ 16) {
				set_custom_element_data(vime_video, "controls-list", /*controlsList*/ ctx[4]);
			}

			if (!current || dirty & /*autoPiP*/ 32) {
				set_custom_element_data(vime_video, "auto-pip", /*autoPiP*/ ctx[5]);
			}

			if (!current || dirty & /*disablePiP*/ 64) {
				set_custom_element_data(vime_video, "disable-pip", /*disablePiP*/ ctx[6]);
			}

			if (!current || dirty & /*disableRemotePlayback*/ 128) {
				set_custom_element_data(vime_video, "disable-remote-playback", /*disableRemotePlayback*/ ctx[7]);
			}

			if (!current || dirty & /*mediaTitle*/ 256) {
				set_custom_element_data(vime_video, "media-title", /*mediaTitle*/ ctx[8]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_video);
			if (default_slot) default_slot.d(detaching);
			/*vime_video_binding*/ ctx[14](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { willAttach = undefined } = $$props;
	let { crossOrigin = undefined } = $$props;
	let { preload = undefined } = $$props;
	let { poster = undefined } = $$props;
	let { controlsList = undefined } = $$props;
	let { autoPiP = undefined } = $$props;
	let { disablePiP = undefined } = $$props;
	let { disableRemotePlayback = undefined } = $$props;
	let { mediaTitle = undefined } = $$props;
	const getAdapter = (...args) => __ref.getAdapter(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(9, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_video_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(9, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("willAttach" in $$props) $$invalidate(0, willAttach = $$props.willAttach);
		if ("crossOrigin" in $$props) $$invalidate(1, crossOrigin = $$props.crossOrigin);
		if ("preload" in $$props) $$invalidate(2, preload = $$props.preload);
		if ("poster" in $$props) $$invalidate(3, poster = $$props.poster);
		if ("controlsList" in $$props) $$invalidate(4, controlsList = $$props.controlsList);
		if ("autoPiP" in $$props) $$invalidate(5, autoPiP = $$props.autoPiP);
		if ("disablePiP" in $$props) $$invalidate(6, disablePiP = $$props.disablePiP);
		if ("disableRemotePlayback" in $$props) $$invalidate(7, disableRemotePlayback = $$props.disableRemotePlayback);
		if ("mediaTitle" in $$props) $$invalidate(8, mediaTitle = $$props.mediaTitle);
		if ("$$scope" in $$props) $$invalidate(12, $$scope = $$props.$$scope);
	};

	return [
		willAttach,
		crossOrigin,
		preload,
		poster,
		controlsList,
		autoPiP,
		disablePiP,
		disableRemotePlayback,
		mediaTitle,
		__ref,
		getAdapter,
		getWebComponent,
		$$scope,
		$$slots,
		vime_video_binding
	];
}

class VimeVideo extends SvelteComponent {
  $$prop_def: VimeVideoProps;
  $$events_def: VimeVideoEvents;
  $$slot_def: VimeVideoSlots;

  $on<K extends keyof VimeVideoEvents>(type: K, callback: (e: VimeVideoEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeVideoProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			willAttach: 0,
			crossOrigin: 1,
			preload: 2,
			poster: 3,
			controlsList: 4,
			autoPiP: 5,
			disablePiP: 6,
			disableRemotePlayback: 7,
			mediaTitle: 8,
			getAdapter: 10,
			getWebComponent: 11
		});
	}

	
  /**  */
 get getAdapter(): Components.VimeVideo["getAdapter"] {
		return this.$$.ctx[10];
	}

	get getWebComponent(): HTMLVimeVideoElement | undefined {
		return this.$$.ctx[11];
	}
}

export default VimeVideo;