/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeMenuRadioGroupProps {
  
  /** The current value selected for this group. */
  value?: Components.VimeMenuRadioGroup["value"]
}

interface VimeMenuRadioGroupEvents {
  
  /** Emitted when a new radio button is selected for this group. */
  vCheck: Parameters<JSX.VimeMenuRadioGroup["onVCheck"]>[0]
}

interface VimeMenuRadioGroupSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_menu_radio_group;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*$$slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			vime_menu_radio_group = element("vime-menu-radio-group");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_menu_radio_group, "value", /*value*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, vime_menu_radio_group, anchor);

			if (default_slot) {
				default_slot.m(vime_menu_radio_group, null);
			}

			/*vime_menu_radio_group_binding*/ ctx[6](vime_menu_radio_group);
			current = true;

			if (!mounted) {
				dispose = listen(vime_menu_radio_group, "vCheck", /*onEvent*/ ctx[2]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}

			if (!current || dirty & /*value*/ 1) {
				set_custom_element_data(vime_menu_radio_group, "value", /*value*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_menu_radio_group);
			if (default_slot) default_slot.d(detaching);
			/*vime_menu_radio_group_binding*/ ctx[6](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { value = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_menu_radio_group_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("value" in $$props) $$invalidate(0, value = $$props.value);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		value,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		$$slots,
		vime_menu_radio_group_binding
	];
}

class VimeMenuRadioGroup extends SvelteComponent {
  $$prop_def: VimeMenuRadioGroupProps;
  $$events_def: VimeMenuRadioGroupEvents;
  $$slot_def: VimeMenuRadioGroupSlots;

  $on<K extends keyof VimeMenuRadioGroupEvents>(type: K, callback: (e: VimeMenuRadioGroupEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeMenuRadioGroupProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { value: 0, getWebComponent: 3 });
	}

	get getWebComponent(): HTMLVimeMenuRadioGroupElement | undefined {
		return this.$$.ctx[3];
	}
}

export default VimeMenuRadioGroup;