/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeCaptionControlProps {
  
  /** The URL to an SVG element or fragment to load. */
  showIcon?: Components.VimeCaptionControl["showIcon"]
  
  /** The URL to an SVG element or fragment to load. */
  hideIcon?: Components.VimeCaptionControl["hideIcon"]
  
  /** The direction in which the tooltip should grow. */
  tooltipDirection?: Components.VimeCaptionControl["tooltipDirection"]
  
  /** Whether the tooltip should not be displayed. */
  hideTooltip?: Components.VimeCaptionControl["hideTooltip"]
  
  /** Scale the size of the control up/down by the amount given. */
  scale?: Components.VimeCaptionControl["scale"]
  
  /** A slash (`/`) separated string of JS keyboard keys (`KeyboardEvent.key`), that when caught in
a `keydown` event, will trigger a `click` event on the control. */
  keys?: Components.VimeCaptionControl["keys"]
  
  /**  */
  currentCaption?: Components.VimeCaptionControl["currentCaption"]
  
  /**  */
  isCaptionsActive?: Components.VimeCaptionControl["isCaptionsActive"]
  
  /**  */
  i18n?: Components.VimeCaptionControl["i18n"]
}

interface VimeCaptionControlEvents {
  
}

interface VimeCaptionControlSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_caption_control;
	let current;
	const default_slot_template = /*$$slots*/ ctx[12].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[11], null);

	return {
		c() {
			vime_caption_control = element("vime-caption-control");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_caption_control, "show-icon", /*showIcon*/ ctx[0]);
			set_custom_element_data(vime_caption_control, "hide-icon", /*hideIcon*/ ctx[1]);
			set_custom_element_data(vime_caption_control, "tooltip-direction", /*tooltipDirection*/ ctx[2]);
			set_custom_element_data(vime_caption_control, "hide-tooltip", /*hideTooltip*/ ctx[3]);
			set_custom_element_data(vime_caption_control, "scale", /*scale*/ ctx[4]);
			set_custom_element_data(vime_caption_control, "keys", /*keys*/ ctx[5]);
			set_custom_element_data(vime_caption_control, "is-captions-active", /*isCaptionsActive*/ ctx[6]);
		},
		m(target, anchor) {
			insert(target, vime_caption_control, anchor);

			if (default_slot) {
				default_slot.m(vime_caption_control, null);
			}

			/*vime_caption_control_binding*/ ctx[13](vime_caption_control);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 2048) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[11], dirty, null, null);
				}
			}

			if (!current || dirty & /*showIcon*/ 1) {
				set_custom_element_data(vime_caption_control, "show-icon", /*showIcon*/ ctx[0]);
			}

			if (!current || dirty & /*hideIcon*/ 2) {
				set_custom_element_data(vime_caption_control, "hide-icon", /*hideIcon*/ ctx[1]);
			}

			if (!current || dirty & /*tooltipDirection*/ 4) {
				set_custom_element_data(vime_caption_control, "tooltip-direction", /*tooltipDirection*/ ctx[2]);
			}

			if (!current || dirty & /*hideTooltip*/ 8) {
				set_custom_element_data(vime_caption_control, "hide-tooltip", /*hideTooltip*/ ctx[3]);
			}

			if (!current || dirty & /*scale*/ 16) {
				set_custom_element_data(vime_caption_control, "scale", /*scale*/ ctx[4]);
			}

			if (!current || dirty & /*keys*/ 32) {
				set_custom_element_data(vime_caption_control, "keys", /*keys*/ ctx[5]);
			}

			if (!current || dirty & /*isCaptionsActive*/ 64) {
				set_custom_element_data(vime_caption_control, "is-captions-active", /*isCaptionsActive*/ ctx[6]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_caption_control);
			if (default_slot) default_slot.d(detaching);
			/*vime_caption_control_binding*/ ctx[13](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { showIcon = undefined } = $$props;
	let { hideIcon = undefined } = $$props;
	let { tooltipDirection = undefined } = $$props;
	let { hideTooltip = undefined } = $$props;
	let { scale = undefined } = $$props;
	let { keys = undefined } = $$props;
	let { currentCaption = undefined } = $$props;
	let { isCaptionsActive = undefined } = $$props;
	let { i18n = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(14, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(7, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_caption_control_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(7, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("showIcon" in $$props) $$invalidate(0, showIcon = $$props.showIcon);
		if ("hideIcon" in $$props) $$invalidate(1, hideIcon = $$props.hideIcon);
		if ("tooltipDirection" in $$props) $$invalidate(2, tooltipDirection = $$props.tooltipDirection);
		if ("hideTooltip" in $$props) $$invalidate(3, hideTooltip = $$props.hideTooltip);
		if ("scale" in $$props) $$invalidate(4, scale = $$props.scale);
		if ("keys" in $$props) $$invalidate(5, keys = $$props.keys);
		if ("currentCaption" in $$props) $$invalidate(8, currentCaption = $$props.currentCaption);
		if ("isCaptionsActive" in $$props) $$invalidate(6, isCaptionsActive = $$props.isCaptionsActive);
		if ("i18n" in $$props) $$invalidate(9, i18n = $$props.i18n);
		if ("$$scope" in $$props) $$invalidate(11, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, currentCaption*/ 16640) {
			$: if (__mounted) setProp("currentCaption", currentCaption);
		}

		if ($$self.$$.dirty & /*__mounted, i18n*/ 16896) {
			$: if (__mounted) setProp("i18n", i18n);
		}
	};

	return [
		showIcon,
		hideIcon,
		tooltipDirection,
		hideTooltip,
		scale,
		keys,
		isCaptionsActive,
		__ref,
		currentCaption,
		i18n,
		getWebComponent,
		$$scope,
		$$slots,
		vime_caption_control_binding
	];
}

class VimeCaptionControl extends SvelteComponent {
  $$prop_def: VimeCaptionControlProps;
  $$events_def: VimeCaptionControlEvents;
  $$slot_def: VimeCaptionControlSlots;

  $on<K extends keyof VimeCaptionControlEvents>(type: K, callback: (e: VimeCaptionControlEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeCaptionControlProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			showIcon: 0,
			hideIcon: 1,
			tooltipDirection: 2,
			hideTooltip: 3,
			scale: 4,
			keys: 5,
			currentCaption: 8,
			isCaptionsActive: 6,
			i18n: 9,
			getWebComponent: 10
		});
	}

	get getWebComponent(): HTMLVimeCaptionControlElement | undefined {
		return this.$$.ctx[10];
	}
}

export default VimeCaptionControl;