/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeCurrentTimeProps {
  
  /**  */
  currentTime?: Components.VimeCurrentTime["currentTime"]
  
  /**  */
  i18n?: Components.VimeCurrentTime["i18n"]
  
  /** Whether the time should always show the hours unit, even if the time is less than
1 hour (eg: `20:35` -> `00:20:35`). */
  alwaysShowHours?: Components.VimeCurrentTime["alwaysShowHours"]
}

interface VimeCurrentTimeEvents {
  
}

interface VimeCurrentTimeSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_current_time;
	let current;
	const default_slot_template = /*$$slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			vime_current_time = element("vime-current-time");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_current_time, "current-time", /*currentTime*/ ctx[0]);
			set_custom_element_data(vime_current_time, "always-show-hours", /*alwaysShowHours*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, vime_current_time, anchor);

			if (default_slot) {
				default_slot.m(vime_current_time, null);
			}

			/*vime_current_time_binding*/ ctx[7](vime_current_time);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[5], dirty, null, null);
				}
			}

			if (!current || dirty & /*currentTime*/ 1) {
				set_custom_element_data(vime_current_time, "current-time", /*currentTime*/ ctx[0]);
			}

			if (!current || dirty & /*alwaysShowHours*/ 2) {
				set_custom_element_data(vime_current_time, "always-show-hours", /*alwaysShowHours*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_current_time);
			if (default_slot) default_slot.d(detaching);
			/*vime_current_time_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { currentTime = undefined } = $$props;
	let { i18n = undefined } = $$props;
	let { alwaysShowHours = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(8, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_current_time_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("currentTime" in $$props) $$invalidate(0, currentTime = $$props.currentTime);
		if ("i18n" in $$props) $$invalidate(3, i18n = $$props.i18n);
		if ("alwaysShowHours" in $$props) $$invalidate(1, alwaysShowHours = $$props.alwaysShowHours);
		if ("$$scope" in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, i18n*/ 264) {
			$: if (__mounted) setProp("i18n", i18n);
		}
	};

	return [
		currentTime,
		alwaysShowHours,
		__ref,
		i18n,
		getWebComponent,
		$$scope,
		$$slots,
		vime_current_time_binding
	];
}

class VimeCurrentTime extends SvelteComponent {
  $$prop_def: VimeCurrentTimeProps;
  $$events_def: VimeCurrentTimeEvents;
  $$slot_def: VimeCurrentTimeSlots;

  $on<K extends keyof VimeCurrentTimeEvents>(type: K, callback: (e: VimeCurrentTimeEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeCurrentTimeProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			currentTime: 0,
			i18n: 3,
			alwaysShowHours: 1,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLVimeCurrentTimeElement | undefined {
		return this.$$.ctx[4];
	}
}

export default VimeCurrentTime;