/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeFileProps {
  
  /**  */
  willAttach?: Components.VimeFile["willAttach"]
  
  /** Whether to use CORS to fetch the related image. See
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) for more
information. */
  crossOrigin?: Components.VimeFile["crossOrigin"]
  
  /** Provides a hint to the browser about what the author thinks will lead to the best user
experience with regards to what content is loaded before the video is played. See
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload) for more
information. */
  preload?: Components.VimeFile["preload"]
  
  /** A URL for an image to be shown while the video is downloading. If this attribute isn't
specified, nothing is displayed until the first frame is available, then the first frame is
shown as the poster frame. */
  poster?: Components.VimeFile["poster"]
  
  /** The title of the current media. */
  mediaTitle?: Components.VimeFile["mediaTitle"]
  
  /** Determines what controls to show on the media element whenever the browser shows its own set
of controls (e.g. when the controls attribute is specified). */
  controlsList?: Components.VimeFile["controlsList"]
  
  /** **EXPERIMENTAL:** Whether the browser should automatically toggle picture-in-picture mode as
the user switches back and forth between this document and another document or application. */
  autoPiP?: Components.VimeFile["autoPiP"]
  
  /** **EXPERIMENTAL:** Prevents the browser from suggesting a picture-in-picture context menu or to
request picture-in-picture automatically in some cases. */
  disablePiP?: Components.VimeFile["disablePiP"]
  
  /** **EXPERIMENTAL:** Whether to disable the capability of remote playback in devices that are
attached using wired (HDMI, DVI, etc.) and wireless technologies
(Miracast, Chromecast, DLNA, AirPlay, etc). */
  disableRemotePlayback?: Components.VimeFile["disableRemotePlayback"]
  
  /** Whether to use an `audio` or `video` element to play the media. */
  viewType?: Components.VimeFile["viewType"]
  
  /** The playback rates that are available for this media. */
  playbackRates?: Components.VimeFile["playbackRates"]
  
  /**  */
  language?: Components.VimeFile["language"]
  
  /**  */
  autoplay?: Components.VimeFile["autoplay"]
  
  /**  */
  controls?: Components.VimeFile["controls"]
  
  /**  */
  debug?: Components.VimeFile["debug"]
  
  /**  */
  loop?: Components.VimeFile["loop"]
  
  /**  */
  muted?: Components.VimeFile["muted"]
  
  /**  */
  playsinline?: Components.VimeFile["playsinline"]
}

interface VimeFileEvents {
  
  /**  */
  vLoadStart: Parameters<JSX.VimeFile["onVLoadStart"]>[0]
}

interface VimeFileSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_file;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*$$slots*/ ctx[23].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[22], null);

	return {
		c() {
			vime_file = element("vime-file");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_file, "will-attach", /*willAttach*/ ctx[0]);
			set_custom_element_data(vime_file, "cross-origin", /*crossOrigin*/ ctx[1]);
			set_custom_element_data(vime_file, "preload", /*preload*/ ctx[2]);
			set_custom_element_data(vime_file, "poster", /*poster*/ ctx[3]);
			set_custom_element_data(vime_file, "media-title", /*mediaTitle*/ ctx[4]);
			set_custom_element_data(vime_file, "controls-list", /*controlsList*/ ctx[5]);
			set_custom_element_data(vime_file, "auto-pip", /*autoPiP*/ ctx[6]);
			set_custom_element_data(vime_file, "disable-pip", /*disablePiP*/ ctx[7]);
			set_custom_element_data(vime_file, "disable-remote-playback", /*disableRemotePlayback*/ ctx[8]);
			set_custom_element_data(vime_file, "view-type", /*viewType*/ ctx[9]);
			set_custom_element_data(vime_file, "language", /*language*/ ctx[10]);
			set_custom_element_data(vime_file, "autoplay", /*autoplay*/ ctx[11]);
			set_custom_element_data(vime_file, "controls", /*controls*/ ctx[12]);
			set_custom_element_data(vime_file, "debug", /*debug*/ ctx[13]);
			set_custom_element_data(vime_file, "loop", /*loop*/ ctx[14]);
			set_custom_element_data(vime_file, "muted", /*muted*/ ctx[15]);
			set_custom_element_data(vime_file, "playsinline", /*playsinline*/ ctx[16]);
		},
		m(target, anchor) {
			insert(target, vime_file, anchor);

			if (default_slot) {
				default_slot.m(vime_file, null);
			}

			/*vime_file_binding*/ ctx[24](vime_file);
			current = true;

			if (!mounted) {
				dispose = listen(vime_file, "vLoadStart", /*onEvent*/ ctx[18]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4194304) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[22], dirty, null, null);
				}
			}

			if (!current || dirty & /*willAttach*/ 1) {
				set_custom_element_data(vime_file, "will-attach", /*willAttach*/ ctx[0]);
			}

			if (!current || dirty & /*crossOrigin*/ 2) {
				set_custom_element_data(vime_file, "cross-origin", /*crossOrigin*/ ctx[1]);
			}

			if (!current || dirty & /*preload*/ 4) {
				set_custom_element_data(vime_file, "preload", /*preload*/ ctx[2]);
			}

			if (!current || dirty & /*poster*/ 8) {
				set_custom_element_data(vime_file, "poster", /*poster*/ ctx[3]);
			}

			if (!current || dirty & /*mediaTitle*/ 16) {
				set_custom_element_data(vime_file, "media-title", /*mediaTitle*/ ctx[4]);
			}

			if (!current || dirty & /*controlsList*/ 32) {
				set_custom_element_data(vime_file, "controls-list", /*controlsList*/ ctx[5]);
			}

			if (!current || dirty & /*autoPiP*/ 64) {
				set_custom_element_data(vime_file, "auto-pip", /*autoPiP*/ ctx[6]);
			}

			if (!current || dirty & /*disablePiP*/ 128) {
				set_custom_element_data(vime_file, "disable-pip", /*disablePiP*/ ctx[7]);
			}

			if (!current || dirty & /*disableRemotePlayback*/ 256) {
				set_custom_element_data(vime_file, "disable-remote-playback", /*disableRemotePlayback*/ ctx[8]);
			}

			if (!current || dirty & /*viewType*/ 512) {
				set_custom_element_data(vime_file, "view-type", /*viewType*/ ctx[9]);
			}

			if (!current || dirty & /*language*/ 1024) {
				set_custom_element_data(vime_file, "language", /*language*/ ctx[10]);
			}

			if (!current || dirty & /*autoplay*/ 2048) {
				set_custom_element_data(vime_file, "autoplay", /*autoplay*/ ctx[11]);
			}

			if (!current || dirty & /*controls*/ 4096) {
				set_custom_element_data(vime_file, "controls", /*controls*/ ctx[12]);
			}

			if (!current || dirty & /*debug*/ 8192) {
				set_custom_element_data(vime_file, "debug", /*debug*/ ctx[13]);
			}

			if (!current || dirty & /*loop*/ 16384) {
				set_custom_element_data(vime_file, "loop", /*loop*/ ctx[14]);
			}

			if (!current || dirty & /*muted*/ 32768) {
				set_custom_element_data(vime_file, "muted", /*muted*/ ctx[15]);
			}

			if (!current || dirty & /*playsinline*/ 65536) {
				set_custom_element_data(vime_file, "playsinline", /*playsinline*/ ctx[16]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_file);
			if (default_slot) default_slot.d(detaching);
			/*vime_file_binding*/ ctx[24](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { willAttach = undefined } = $$props;
	let { crossOrigin = undefined } = $$props;
	let { preload = undefined } = $$props;
	let { poster = undefined } = $$props;
	let { mediaTitle = undefined } = $$props;
	let { controlsList = undefined } = $$props;
	let { autoPiP = undefined } = $$props;
	let { disablePiP = undefined } = $$props;
	let { disableRemotePlayback = undefined } = $$props;
	let { viewType = undefined } = $$props;
	let { playbackRates = undefined } = $$props;
	let { language = undefined } = $$props;
	let { autoplay = undefined } = $$props;
	let { controls = undefined } = $$props;
	let { debug = undefined } = $$props;
	let { loop = undefined } = $$props;
	let { muted = undefined } = $$props;
	let { playsinline = undefined } = $$props;
	const getAdapter = (...args) => __ref.getAdapter(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(25, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(17, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_file_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(17, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("willAttach" in $$props) $$invalidate(0, willAttach = $$props.willAttach);
		if ("crossOrigin" in $$props) $$invalidate(1, crossOrigin = $$props.crossOrigin);
		if ("preload" in $$props) $$invalidate(2, preload = $$props.preload);
		if ("poster" in $$props) $$invalidate(3, poster = $$props.poster);
		if ("mediaTitle" in $$props) $$invalidate(4, mediaTitle = $$props.mediaTitle);
		if ("controlsList" in $$props) $$invalidate(5, controlsList = $$props.controlsList);
		if ("autoPiP" in $$props) $$invalidate(6, autoPiP = $$props.autoPiP);
		if ("disablePiP" in $$props) $$invalidate(7, disablePiP = $$props.disablePiP);
		if ("disableRemotePlayback" in $$props) $$invalidate(8, disableRemotePlayback = $$props.disableRemotePlayback);
		if ("viewType" in $$props) $$invalidate(9, viewType = $$props.viewType);
		if ("playbackRates" in $$props) $$invalidate(19, playbackRates = $$props.playbackRates);
		if ("language" in $$props) $$invalidate(10, language = $$props.language);
		if ("autoplay" in $$props) $$invalidate(11, autoplay = $$props.autoplay);
		if ("controls" in $$props) $$invalidate(12, controls = $$props.controls);
		if ("debug" in $$props) $$invalidate(13, debug = $$props.debug);
		if ("loop" in $$props) $$invalidate(14, loop = $$props.loop);
		if ("muted" in $$props) $$invalidate(15, muted = $$props.muted);
		if ("playsinline" in $$props) $$invalidate(16, playsinline = $$props.playsinline);
		if ("$$scope" in $$props) $$invalidate(22, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, playbackRates*/ 34078720) {
			$: if (__mounted) setProp("playbackRates", playbackRates);
		}
	};

	return [
		willAttach,
		crossOrigin,
		preload,
		poster,
		mediaTitle,
		controlsList,
		autoPiP,
		disablePiP,
		disableRemotePlayback,
		viewType,
		language,
		autoplay,
		controls,
		debug,
		loop,
		muted,
		playsinline,
		__ref,
		onEvent,
		playbackRates,
		getAdapter,
		getWebComponent,
		$$scope,
		$$slots,
		vime_file_binding
	];
}

class VimeFile extends SvelteComponent {
  $$prop_def: VimeFileProps;
  $$events_def: VimeFileEvents;
  $$slot_def: VimeFileSlots;

  $on<K extends keyof VimeFileEvents>(type: K, callback: (e: VimeFileEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeFileProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			willAttach: 0,
			crossOrigin: 1,
			preload: 2,
			poster: 3,
			mediaTitle: 4,
			controlsList: 5,
			autoPiP: 6,
			disablePiP: 7,
			disableRemotePlayback: 8,
			viewType: 9,
			playbackRates: 19,
			language: 10,
			autoplay: 11,
			controls: 12,
			debug: 13,
			loop: 14,
			muted: 15,
			playsinline: 16,
			getAdapter: 20,
			getWebComponent: 21
		});
	}

	
  /**  */
 get getAdapter(): Components.VimeFile["getAdapter"] {
		return this.$$.ctx[20];
	}

	get getWebComponent(): HTMLVimeFileElement | undefined {
		return this.$$.ctx[21];
	}
}

export default VimeFile;