/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeVolumeControlProps {
  
  /** The URL to an SVG element or fragment. */
  lowVolumeIcon?: Components.VimeVolumeControl["lowVolumeIcon"]
  
  /** The URL to an SVG element or fragment. */
  highVolumeIcon?: Components.VimeVolumeControl["highVolumeIcon"]
  
  /** The URL to an SVG element or fragment. */
  mutedIcon?: Components.VimeVolumeControl["mutedIcon"]
  
  /** The direction in which the tooltip should grow. */
  tooltipDirection?: Components.VimeVolumeControl["tooltipDirection"]
  
  /** Whether the tooltip should be hidden. */
  hideTooltip?: Components.VimeVolumeControl["hideTooltip"]
  
  /** A pipe (`/`) seperated string of JS keyboard keys, that when caught in a `keydown` event, will
toggle the muted state of the player. */
  muteKeys?: Components.VimeVolumeControl["muteKeys"]
  
  /** Prevents the volume being changed using the Up/Down arrow keys. */
  noKeyboard?: Components.VimeVolumeControl["noKeyboard"]
  
  /**  */
  muted?: Components.VimeVolumeControl["muted"]
  
  /**  */
  volume?: Components.VimeVolumeControl["volume"]
  
  /**  */
  isMobile?: Components.VimeVolumeControl["isMobile"]
  
  /**  */
  i18n?: Components.VimeVolumeControl["i18n"]
}

interface VimeVolumeControlEvents {
  
}

interface VimeVolumeControlSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_volume_control;
	let current;
	const default_slot_template = /*$$slots*/ ctx[14].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[13], null);

	return {
		c() {
			vime_volume_control = element("vime-volume-control");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_volume_control, "low-volume-icon", /*lowVolumeIcon*/ ctx[0]);
			set_custom_element_data(vime_volume_control, "high-volume-icon", /*highVolumeIcon*/ ctx[1]);
			set_custom_element_data(vime_volume_control, "muted-icon", /*mutedIcon*/ ctx[2]);
			set_custom_element_data(vime_volume_control, "tooltip-direction", /*tooltipDirection*/ ctx[3]);
			set_custom_element_data(vime_volume_control, "hide-tooltip", /*hideTooltip*/ ctx[4]);
			set_custom_element_data(vime_volume_control, "mute-keys", /*muteKeys*/ ctx[5]);
			set_custom_element_data(vime_volume_control, "no-keyboard", /*noKeyboard*/ ctx[6]);
			set_custom_element_data(vime_volume_control, "muted", /*muted*/ ctx[7]);
			set_custom_element_data(vime_volume_control, "volume", /*volume*/ ctx[8]);
			set_custom_element_data(vime_volume_control, "is-mobile", /*isMobile*/ ctx[9]);
		},
		m(target, anchor) {
			insert(target, vime_volume_control, anchor);

			if (default_slot) {
				default_slot.m(vime_volume_control, null);
			}

			/*vime_volume_control_binding*/ ctx[15](vime_volume_control);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8192) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[13], dirty, null, null);
				}
			}

			if (!current || dirty & /*lowVolumeIcon*/ 1) {
				set_custom_element_data(vime_volume_control, "low-volume-icon", /*lowVolumeIcon*/ ctx[0]);
			}

			if (!current || dirty & /*highVolumeIcon*/ 2) {
				set_custom_element_data(vime_volume_control, "high-volume-icon", /*highVolumeIcon*/ ctx[1]);
			}

			if (!current || dirty & /*mutedIcon*/ 4) {
				set_custom_element_data(vime_volume_control, "muted-icon", /*mutedIcon*/ ctx[2]);
			}

			if (!current || dirty & /*tooltipDirection*/ 8) {
				set_custom_element_data(vime_volume_control, "tooltip-direction", /*tooltipDirection*/ ctx[3]);
			}

			if (!current || dirty & /*hideTooltip*/ 16) {
				set_custom_element_data(vime_volume_control, "hide-tooltip", /*hideTooltip*/ ctx[4]);
			}

			if (!current || dirty & /*muteKeys*/ 32) {
				set_custom_element_data(vime_volume_control, "mute-keys", /*muteKeys*/ ctx[5]);
			}

			if (!current || dirty & /*noKeyboard*/ 64) {
				set_custom_element_data(vime_volume_control, "no-keyboard", /*noKeyboard*/ ctx[6]);
			}

			if (!current || dirty & /*muted*/ 128) {
				set_custom_element_data(vime_volume_control, "muted", /*muted*/ ctx[7]);
			}

			if (!current || dirty & /*volume*/ 256) {
				set_custom_element_data(vime_volume_control, "volume", /*volume*/ ctx[8]);
			}

			if (!current || dirty & /*isMobile*/ 512) {
				set_custom_element_data(vime_volume_control, "is-mobile", /*isMobile*/ ctx[9]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_volume_control);
			if (default_slot) default_slot.d(detaching);
			/*vime_volume_control_binding*/ ctx[15](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { lowVolumeIcon = undefined } = $$props;
	let { highVolumeIcon = undefined } = $$props;
	let { mutedIcon = undefined } = $$props;
	let { tooltipDirection = undefined } = $$props;
	let { hideTooltip = undefined } = $$props;
	let { muteKeys = undefined } = $$props;
	let { noKeyboard = undefined } = $$props;
	let { muted = undefined } = $$props;
	let { volume = undefined } = $$props;
	let { isMobile = undefined } = $$props;
	let { i18n = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(16, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(10, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_volume_control_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(10, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("lowVolumeIcon" in $$props) $$invalidate(0, lowVolumeIcon = $$props.lowVolumeIcon);
		if ("highVolumeIcon" in $$props) $$invalidate(1, highVolumeIcon = $$props.highVolumeIcon);
		if ("mutedIcon" in $$props) $$invalidate(2, mutedIcon = $$props.mutedIcon);
		if ("tooltipDirection" in $$props) $$invalidate(3, tooltipDirection = $$props.tooltipDirection);
		if ("hideTooltip" in $$props) $$invalidate(4, hideTooltip = $$props.hideTooltip);
		if ("muteKeys" in $$props) $$invalidate(5, muteKeys = $$props.muteKeys);
		if ("noKeyboard" in $$props) $$invalidate(6, noKeyboard = $$props.noKeyboard);
		if ("muted" in $$props) $$invalidate(7, muted = $$props.muted);
		if ("volume" in $$props) $$invalidate(8, volume = $$props.volume);
		if ("isMobile" in $$props) $$invalidate(9, isMobile = $$props.isMobile);
		if ("i18n" in $$props) $$invalidate(11, i18n = $$props.i18n);
		if ("$$scope" in $$props) $$invalidate(13, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, i18n*/ 67584) {
			$: if (__mounted) setProp("i18n", i18n);
		}
	};

	return [
		lowVolumeIcon,
		highVolumeIcon,
		mutedIcon,
		tooltipDirection,
		hideTooltip,
		muteKeys,
		noKeyboard,
		muted,
		volume,
		isMobile,
		__ref,
		i18n,
		getWebComponent,
		$$scope,
		$$slots,
		vime_volume_control_binding
	];
}

class VimeVolumeControl extends SvelteComponent {
  $$prop_def: VimeVolumeControlProps;
  $$events_def: VimeVolumeControlEvents;
  $$slot_def: VimeVolumeControlSlots;

  $on<K extends keyof VimeVolumeControlEvents>(type: K, callback: (e: VimeVolumeControlEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeVolumeControlProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			lowVolumeIcon: 0,
			highVolumeIcon: 1,
			mutedIcon: 2,
			tooltipDirection: 3,
			hideTooltip: 4,
			muteKeys: 5,
			noKeyboard: 6,
			muted: 7,
			volume: 8,
			isMobile: 9,
			i18n: 11,
			getWebComponent: 12
		});
	}

	get getWebComponent(): HTMLVimeVolumeControlElement | undefined {
		return this.$$.ctx[12];
	}
}

export default VimeVolumeControl;