/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeMuteControlProps {
  
  /** The URL to an SVG element or fragment. */
  lowVolumeIcon?: Components.VimeMuteControl["lowVolumeIcon"]
  
  /** The URL to an SVG element or fragment. */
  highVolumeIcon?: Components.VimeMuteControl["highVolumeIcon"]
  
  /** The URL to an SVG element or fragment. */
  mutedIcon?: Components.VimeMuteControl["mutedIcon"]
  
  /** The direction in which the tooltip should grow. */
  tooltipDirection?: Components.VimeMuteControl["tooltipDirection"]
  
  /** Whether the tooltip should not be displayed. */
  hideTooltip?: Components.VimeMuteControl["hideTooltip"]
  
  /** Scale the size of the control up/down by the amount given. */
  scale?: Components.VimeMuteControl["scale"]
  
  /** A slash (`/`) separated string of JS keyboard keys (`KeyboardEvent.key`), that when caught in
a `keydown` event, will trigger a `click` event on the control. */
  keys?: Components.VimeMuteControl["keys"]
  
  /**  */
  volume?: Components.VimeMuteControl["volume"]
  
  /**  */
  muted?: Components.VimeMuteControl["muted"]
  
  /**  */
  i18n?: Components.VimeMuteControl["i18n"]
}

interface VimeMuteControlEvents {
  
}

interface VimeMuteControlSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_mute_control;
	let current;
	const default_slot_template = /*$$slots*/ ctx[13].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[12], null);

	return {
		c() {
			vime_mute_control = element("vime-mute-control");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_mute_control, "low-volume-icon", /*lowVolumeIcon*/ ctx[0]);
			set_custom_element_data(vime_mute_control, "high-volume-icon", /*highVolumeIcon*/ ctx[1]);
			set_custom_element_data(vime_mute_control, "muted-icon", /*mutedIcon*/ ctx[2]);
			set_custom_element_data(vime_mute_control, "tooltip-direction", /*tooltipDirection*/ ctx[3]);
			set_custom_element_data(vime_mute_control, "hide-tooltip", /*hideTooltip*/ ctx[4]);
			set_custom_element_data(vime_mute_control, "scale", /*scale*/ ctx[5]);
			set_custom_element_data(vime_mute_control, "keys", /*keys*/ ctx[6]);
			set_custom_element_data(vime_mute_control, "volume", /*volume*/ ctx[7]);
			set_custom_element_data(vime_mute_control, "muted", /*muted*/ ctx[8]);
		},
		m(target, anchor) {
			insert(target, vime_mute_control, anchor);

			if (default_slot) {
				default_slot.m(vime_mute_control, null);
			}

			/*vime_mute_control_binding*/ ctx[14](vime_mute_control);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4096) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[12], dirty, null, null);
				}
			}

			if (!current || dirty & /*lowVolumeIcon*/ 1) {
				set_custom_element_data(vime_mute_control, "low-volume-icon", /*lowVolumeIcon*/ ctx[0]);
			}

			if (!current || dirty & /*highVolumeIcon*/ 2) {
				set_custom_element_data(vime_mute_control, "high-volume-icon", /*highVolumeIcon*/ ctx[1]);
			}

			if (!current || dirty & /*mutedIcon*/ 4) {
				set_custom_element_data(vime_mute_control, "muted-icon", /*mutedIcon*/ ctx[2]);
			}

			if (!current || dirty & /*tooltipDirection*/ 8) {
				set_custom_element_data(vime_mute_control, "tooltip-direction", /*tooltipDirection*/ ctx[3]);
			}

			if (!current || dirty & /*hideTooltip*/ 16) {
				set_custom_element_data(vime_mute_control, "hide-tooltip", /*hideTooltip*/ ctx[4]);
			}

			if (!current || dirty & /*scale*/ 32) {
				set_custom_element_data(vime_mute_control, "scale", /*scale*/ ctx[5]);
			}

			if (!current || dirty & /*keys*/ 64) {
				set_custom_element_data(vime_mute_control, "keys", /*keys*/ ctx[6]);
			}

			if (!current || dirty & /*volume*/ 128) {
				set_custom_element_data(vime_mute_control, "volume", /*volume*/ ctx[7]);
			}

			if (!current || dirty & /*muted*/ 256) {
				set_custom_element_data(vime_mute_control, "muted", /*muted*/ ctx[8]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_mute_control);
			if (default_slot) default_slot.d(detaching);
			/*vime_mute_control_binding*/ ctx[14](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { lowVolumeIcon = undefined } = $$props;
	let { highVolumeIcon = undefined } = $$props;
	let { mutedIcon = undefined } = $$props;
	let { tooltipDirection = undefined } = $$props;
	let { hideTooltip = undefined } = $$props;
	let { scale = undefined } = $$props;
	let { keys = undefined } = $$props;
	let { volume = undefined } = $$props;
	let { muted = undefined } = $$props;
	let { i18n = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(15, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(9, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_mute_control_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(9, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("lowVolumeIcon" in $$props) $$invalidate(0, lowVolumeIcon = $$props.lowVolumeIcon);
		if ("highVolumeIcon" in $$props) $$invalidate(1, highVolumeIcon = $$props.highVolumeIcon);
		if ("mutedIcon" in $$props) $$invalidate(2, mutedIcon = $$props.mutedIcon);
		if ("tooltipDirection" in $$props) $$invalidate(3, tooltipDirection = $$props.tooltipDirection);
		if ("hideTooltip" in $$props) $$invalidate(4, hideTooltip = $$props.hideTooltip);
		if ("scale" in $$props) $$invalidate(5, scale = $$props.scale);
		if ("keys" in $$props) $$invalidate(6, keys = $$props.keys);
		if ("volume" in $$props) $$invalidate(7, volume = $$props.volume);
		if ("muted" in $$props) $$invalidate(8, muted = $$props.muted);
		if ("i18n" in $$props) $$invalidate(10, i18n = $$props.i18n);
		if ("$$scope" in $$props) $$invalidate(12, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, i18n*/ 33792) {
			$: if (__mounted) setProp("i18n", i18n);
		}
	};

	return [
		lowVolumeIcon,
		highVolumeIcon,
		mutedIcon,
		tooltipDirection,
		hideTooltip,
		scale,
		keys,
		volume,
		muted,
		__ref,
		i18n,
		getWebComponent,
		$$scope,
		$$slots,
		vime_mute_control_binding
	];
}

class VimeMuteControl extends SvelteComponent {
  $$prop_def: VimeMuteControlProps;
  $$events_def: VimeMuteControlEvents;
  $$slot_def: VimeMuteControlSlots;

  $on<K extends keyof VimeMuteControlEvents>(type: K, callback: (e: VimeMuteControlEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeMuteControlProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			lowVolumeIcon: 0,
			highVolumeIcon: 1,
			mutedIcon: 2,
			tooltipDirection: 3,
			hideTooltip: 4,
			scale: 5,
			keys: 6,
			volume: 7,
			muted: 8,
			i18n: 10,
			getWebComponent: 11
		});
	}

	get getWebComponent(): HTMLVimeMuteControlElement | undefined {
		return this.$$.ctx[11];
	}
}

export default VimeMuteControl;