/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeScrimProps {
  
  /** If this prop is defined, a dark gradient that smoothly fades out without being noticed will be
used instead of a set color. This prop also sets the direction in which the dark end of the
gradient should start. If the direction is set to `up`, the dark end of the gradient will
start at the bottom of the player and fade out to the center. If the direction is set to
`down`, the gradient will start at the top of the player and fade out to the center. */
  gradient?: Components.VimeScrim["gradient"]
  
  /**  */
  isVideoView?: Components.VimeScrim["isVideoView"]
  
  /**  */
  isControlsActive?: Components.VimeScrim["isControlsActive"]
}

interface VimeScrimEvents {
  
}

interface VimeScrimSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_scrim;
	let current;
	const default_slot_template = /*$$slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			vime_scrim = element("vime-scrim");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_scrim, "gradient", /*gradient*/ ctx[0]);
			set_custom_element_data(vime_scrim, "is-video-view", /*isVideoView*/ ctx[1]);
			set_custom_element_data(vime_scrim, "is-controls-active", /*isControlsActive*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, vime_scrim, anchor);

			if (default_slot) {
				default_slot.m(vime_scrim, null);
			}

			/*vime_scrim_binding*/ ctx[7](vime_scrim);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[5], dirty, null, null);
				}
			}

			if (!current || dirty & /*gradient*/ 1) {
				set_custom_element_data(vime_scrim, "gradient", /*gradient*/ ctx[0]);
			}

			if (!current || dirty & /*isVideoView*/ 2) {
				set_custom_element_data(vime_scrim, "is-video-view", /*isVideoView*/ ctx[1]);
			}

			if (!current || dirty & /*isControlsActive*/ 4) {
				set_custom_element_data(vime_scrim, "is-controls-active", /*isControlsActive*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_scrim);
			if (default_slot) default_slot.d(detaching);
			/*vime_scrim_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { gradient = undefined } = $$props;
	let { isVideoView = undefined } = $$props;
	let { isControlsActive = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_scrim_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("gradient" in $$props) $$invalidate(0, gradient = $$props.gradient);
		if ("isVideoView" in $$props) $$invalidate(1, isVideoView = $$props.isVideoView);
		if ("isControlsActive" in $$props) $$invalidate(2, isControlsActive = $$props.isControlsActive);
		if ("$$scope" in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	return [
		gradient,
		isVideoView,
		isControlsActive,
		__ref,
		getWebComponent,
		$$scope,
		$$slots,
		vime_scrim_binding
	];
}

class VimeScrim extends SvelteComponent {
  $$prop_def: VimeScrimProps;
  $$events_def: VimeScrimEvents;
  $$slot_def: VimeScrimSlots;

  $on<K extends keyof VimeScrimEvents>(type: K, callback: (e: VimeScrimEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeScrimProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			gradient: 0,
			isVideoView: 1,
			isControlsActive: 2,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLVimeScrimElement | undefined {
		return this.$$.ctx[4];
	}
}

export default VimeScrim;