/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeDefaultUiProps {
  
  /** Whether the default icons should not be loaded. */
  noIcons?: Components.VimeDefaultUi["noIcons"]
  
  /** Whether clicking the player should not toggle playback. */
  noClickToPlay?: Components.VimeDefaultUi["noClickToPlay"]
  
  /** Whether the custom captions UI should not be loaded. */
  noCaptions?: Components.VimeDefaultUi["noCaptions"]
  
  /** Whether the custom poster UI should not be loaded. */
  noPoster?: Components.VimeDefaultUi["noPoster"]
  
  /** Whether the custom spinner UI should not be loaded. */
  noSpinner?: Components.VimeDefaultUi["noSpinner"]
  
  /** Whether the custom default controls should not be loaded. */
  noControls?: Components.VimeDefaultUi["noControls"]
  
  /** Whether the custom default settings menu should not be loaded. */
  noSettings?: Components.VimeDefaultUi["noSettings"]
}

interface VimeDefaultUiEvents {
  
}

interface VimeDefaultUiSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_default_ui;
	let current;
	const default_slot_template = /*$$slots*/ ctx[10].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[9], null);

	return {
		c() {
			vime_default_ui = element("vime-default-ui");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_default_ui, "no-icons", /*noIcons*/ ctx[0]);
			set_custom_element_data(vime_default_ui, "no-click-to-play", /*noClickToPlay*/ ctx[1]);
			set_custom_element_data(vime_default_ui, "no-captions", /*noCaptions*/ ctx[2]);
			set_custom_element_data(vime_default_ui, "no-poster", /*noPoster*/ ctx[3]);
			set_custom_element_data(vime_default_ui, "no-spinner", /*noSpinner*/ ctx[4]);
			set_custom_element_data(vime_default_ui, "no-controls", /*noControls*/ ctx[5]);
			set_custom_element_data(vime_default_ui, "no-settings", /*noSettings*/ ctx[6]);
		},
		m(target, anchor) {
			insert(target, vime_default_ui, anchor);

			if (default_slot) {
				default_slot.m(vime_default_ui, null);
			}

			/*vime_default_ui_binding*/ ctx[11](vime_default_ui);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 512) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[9], dirty, null, null);
				}
			}

			if (!current || dirty & /*noIcons*/ 1) {
				set_custom_element_data(vime_default_ui, "no-icons", /*noIcons*/ ctx[0]);
			}

			if (!current || dirty & /*noClickToPlay*/ 2) {
				set_custom_element_data(vime_default_ui, "no-click-to-play", /*noClickToPlay*/ ctx[1]);
			}

			if (!current || dirty & /*noCaptions*/ 4) {
				set_custom_element_data(vime_default_ui, "no-captions", /*noCaptions*/ ctx[2]);
			}

			if (!current || dirty & /*noPoster*/ 8) {
				set_custom_element_data(vime_default_ui, "no-poster", /*noPoster*/ ctx[3]);
			}

			if (!current || dirty & /*noSpinner*/ 16) {
				set_custom_element_data(vime_default_ui, "no-spinner", /*noSpinner*/ ctx[4]);
			}

			if (!current || dirty & /*noControls*/ 32) {
				set_custom_element_data(vime_default_ui, "no-controls", /*noControls*/ ctx[5]);
			}

			if (!current || dirty & /*noSettings*/ 64) {
				set_custom_element_data(vime_default_ui, "no-settings", /*noSettings*/ ctx[6]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_default_ui);
			if (default_slot) default_slot.d(detaching);
			/*vime_default_ui_binding*/ ctx[11](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { noIcons = undefined } = $$props;
	let { noClickToPlay = undefined } = $$props;
	let { noCaptions = undefined } = $$props;
	let { noPoster = undefined } = $$props;
	let { noSpinner = undefined } = $$props;
	let { noControls = undefined } = $$props;
	let { noSettings = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(7, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_default_ui_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(7, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("noIcons" in $$props) $$invalidate(0, noIcons = $$props.noIcons);
		if ("noClickToPlay" in $$props) $$invalidate(1, noClickToPlay = $$props.noClickToPlay);
		if ("noCaptions" in $$props) $$invalidate(2, noCaptions = $$props.noCaptions);
		if ("noPoster" in $$props) $$invalidate(3, noPoster = $$props.noPoster);
		if ("noSpinner" in $$props) $$invalidate(4, noSpinner = $$props.noSpinner);
		if ("noControls" in $$props) $$invalidate(5, noControls = $$props.noControls);
		if ("noSettings" in $$props) $$invalidate(6, noSettings = $$props.noSettings);
		if ("$$scope" in $$props) $$invalidate(9, $$scope = $$props.$$scope);
	};

	return [
		noIcons,
		noClickToPlay,
		noCaptions,
		noPoster,
		noSpinner,
		noControls,
		noSettings,
		__ref,
		getWebComponent,
		$$scope,
		$$slots,
		vime_default_ui_binding
	];
}

class VimeDefaultUi extends SvelteComponent {
  $$prop_def: VimeDefaultUiProps;
  $$events_def: VimeDefaultUiEvents;
  $$slot_def: VimeDefaultUiSlots;

  $on<K extends keyof VimeDefaultUiEvents>(type: K, callback: (e: VimeDefaultUiEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeDefaultUiProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			noIcons: 0,
			noClickToPlay: 1,
			noCaptions: 2,
			noPoster: 3,
			noSpinner: 4,
			noControls: 5,
			noSettings: 6,
			getWebComponent: 8
		});
	}

	get getWebComponent(): HTMLVimeDefaultUiElement | undefined {
		return this.$$.ctx[8];
	}
}

export default VimeDefaultUi;