/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeIconsProps {
  
  /** The URL to an SVG sprite to load. */
  href?: Components.VimeIcons["href"]
}

interface VimeIconsEvents {
  
}

interface VimeIconsSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_icons;
	let current;
	const default_slot_template = /*$$slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	return {
		c() {
			vime_icons = element("vime-icons");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_icons, "href", /*href*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, vime_icons, anchor);

			if (default_slot) {
				default_slot.m(vime_icons, null);
			}

			/*vime_icons_binding*/ ctx[5](vime_icons);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[3], dirty, null, null);
				}
			}

			if (!current || dirty & /*href*/ 1) {
				set_custom_element_data(vime_icons, "href", /*href*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_icons);
			if (default_slot) default_slot.d(detaching);
			/*vime_icons_binding*/ ctx[5](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { href = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_icons_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("href" in $$props) $$invalidate(0, href = $$props.href);
		if ("$$scope" in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [href, __ref, getWebComponent, $$scope, $$slots, vime_icons_binding];
}

class VimeIcons extends SvelteComponent {
  $$prop_def: VimeIconsProps;
  $$events_def: VimeIconsEvents;
  $$slot_def: VimeIconsSlots;

  $on<K extends keyof VimeIconsEvents>(type: K, callback: (e: VimeIconsEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeIconsProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { href: 0, getWebComponent: 2 });
	}

	get getWebComponent(): HTMLVimeIconsElement | undefined {
		return this.$$.ctx[2];
	}
}

export default VimeIcons;