/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@vime/core';


interface VimeVimeoProps {
  
  /** The Vimeo resource ID of the video to load. */
  videoId?: Components.VimeVimeo["videoId"]
  
  /** Whether to display the video owner's name. */
  byline?: Components.VimeVimeo["byline"]
  
  /** The hexadecimal color value of the playback controls. The embed settings of the video
might override this value. */
  color?: Components.VimeVimeo["color"]
  
  /** Whether to display the video owner's portrait. */
  portrait?: Components.VimeVimeo["portrait"]
  
  /**  */
  language?: Components.VimeVimeo["language"]
  
  /**  */
  autoplay?: Components.VimeVimeo["autoplay"]
  
  /**  */
  controls?: Components.VimeVimeo["controls"]
  
  /**  */
  debug?: Components.VimeVimeo["debug"]
  
  /**  */
  loop?: Components.VimeVimeo["loop"]
  
  /**  */
  muted?: Components.VimeVimeo["muted"]
  
  /**  */
  playsinline?: Components.VimeVimeo["playsinline"]
}

interface VimeVimeoEvents {
  
  /**  */
  vLoadStart: Parameters<JSX.VimeVimeo["onVLoadStart"]>[0]
}

interface VimeVimeoSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let vime_vimeo;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*$$slots*/ ctx[16].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[15], null);

	return {
		c() {
			vime_vimeo = element("vime-vimeo");
			if (default_slot) default_slot.c();
			set_custom_element_data(vime_vimeo, "video-id", /*videoId*/ ctx[0]);
			set_custom_element_data(vime_vimeo, "byline", /*byline*/ ctx[1]);
			set_custom_element_data(vime_vimeo, "color", /*color*/ ctx[2]);
			set_custom_element_data(vime_vimeo, "portrait", /*portrait*/ ctx[3]);
			set_custom_element_data(vime_vimeo, "language", /*language*/ ctx[4]);
			set_custom_element_data(vime_vimeo, "autoplay", /*autoplay*/ ctx[5]);
			set_custom_element_data(vime_vimeo, "controls", /*controls*/ ctx[6]);
			set_custom_element_data(vime_vimeo, "debug", /*debug*/ ctx[7]);
			set_custom_element_data(vime_vimeo, "loop", /*loop*/ ctx[8]);
			set_custom_element_data(vime_vimeo, "muted", /*muted*/ ctx[9]);
			set_custom_element_data(vime_vimeo, "playsinline", /*playsinline*/ ctx[10]);
		},
		m(target, anchor) {
			insert(target, vime_vimeo, anchor);

			if (default_slot) {
				default_slot.m(vime_vimeo, null);
			}

			/*vime_vimeo_binding*/ ctx[17](vime_vimeo);
			current = true;

			if (!mounted) {
				dispose = listen(vime_vimeo, "vLoadStart", /*onEvent*/ ctx[12]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32768) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[15], dirty, null, null);
				}
			}

			if (!current || dirty & /*videoId*/ 1) {
				set_custom_element_data(vime_vimeo, "video-id", /*videoId*/ ctx[0]);
			}

			if (!current || dirty & /*byline*/ 2) {
				set_custom_element_data(vime_vimeo, "byline", /*byline*/ ctx[1]);
			}

			if (!current || dirty & /*color*/ 4) {
				set_custom_element_data(vime_vimeo, "color", /*color*/ ctx[2]);
			}

			if (!current || dirty & /*portrait*/ 8) {
				set_custom_element_data(vime_vimeo, "portrait", /*portrait*/ ctx[3]);
			}

			if (!current || dirty & /*language*/ 16) {
				set_custom_element_data(vime_vimeo, "language", /*language*/ ctx[4]);
			}

			if (!current || dirty & /*autoplay*/ 32) {
				set_custom_element_data(vime_vimeo, "autoplay", /*autoplay*/ ctx[5]);
			}

			if (!current || dirty & /*controls*/ 64) {
				set_custom_element_data(vime_vimeo, "controls", /*controls*/ ctx[6]);
			}

			if (!current || dirty & /*debug*/ 128) {
				set_custom_element_data(vime_vimeo, "debug", /*debug*/ ctx[7]);
			}

			if (!current || dirty & /*loop*/ 256) {
				set_custom_element_data(vime_vimeo, "loop", /*loop*/ ctx[8]);
			}

			if (!current || dirty & /*muted*/ 512) {
				set_custom_element_data(vime_vimeo, "muted", /*muted*/ ctx[9]);
			}

			if (!current || dirty & /*playsinline*/ 1024) {
				set_custom_element_data(vime_vimeo, "playsinline", /*playsinline*/ ctx[10]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(vime_vimeo);
			if (default_slot) default_slot.d(detaching);
			/*vime_vimeo_binding*/ ctx[17](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { videoId } = $$props;
	let { byline = undefined } = $$props;
	let { color = undefined } = $$props;
	let { portrait = undefined } = $$props;
	let { language = undefined } = $$props;
	let { autoplay = undefined } = $$props;
	let { controls = undefined } = $$props;
	let { debug = undefined } = $$props;
	let { loop = undefined } = $$props;
	let { muted = undefined } = $$props;
	let { playsinline = undefined } = $$props;
	const getAdapter = (...args) => __ref.getAdapter(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(11, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function vime_vimeo_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(11, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("videoId" in $$props) $$invalidate(0, videoId = $$props.videoId);
		if ("byline" in $$props) $$invalidate(1, byline = $$props.byline);
		if ("color" in $$props) $$invalidate(2, color = $$props.color);
		if ("portrait" in $$props) $$invalidate(3, portrait = $$props.portrait);
		if ("language" in $$props) $$invalidate(4, language = $$props.language);
		if ("autoplay" in $$props) $$invalidate(5, autoplay = $$props.autoplay);
		if ("controls" in $$props) $$invalidate(6, controls = $$props.controls);
		if ("debug" in $$props) $$invalidate(7, debug = $$props.debug);
		if ("loop" in $$props) $$invalidate(8, loop = $$props.loop);
		if ("muted" in $$props) $$invalidate(9, muted = $$props.muted);
		if ("playsinline" in $$props) $$invalidate(10, playsinline = $$props.playsinline);
		if ("$$scope" in $$props) $$invalidate(15, $$scope = $$props.$$scope);
	};

	return [
		videoId,
		byline,
		color,
		portrait,
		language,
		autoplay,
		controls,
		debug,
		loop,
		muted,
		playsinline,
		__ref,
		onEvent,
		getAdapter,
		getWebComponent,
		$$scope,
		$$slots,
		vime_vimeo_binding
	];
}

class VimeVimeo extends SvelteComponent {
  $$prop_def: VimeVimeoProps;
  $$events_def: VimeVimeoEvents;
  $$slot_def: VimeVimeoSlots;

  $on<K extends keyof VimeVimeoEvents>(type: K, callback: (e: VimeVimeoEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<VimeVimeoProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			videoId: 0,
			byline: 1,
			color: 2,
			portrait: 3,
			language: 4,
			autoplay: 5,
			controls: 6,
			debug: 7,
			loop: 8,
			muted: 9,
			playsinline: 10,
			getAdapter: 13,
			getWebComponent: 14
		});
	}

	
  /**  */
 get getAdapter(): Components.VimeVimeo["getAdapter"] {
		return this.$$.ctx[13];
	}

	get getWebComponent(): HTMLVimeVimeoElement | undefined {
		return this.$$.ctx[14];
	}
}

export default VimeVimeo;